package EnodeB.Components;

import java.awt.event.ActionEvent;

public class EnodeBComponentEvent extends ActionEvent{

	/**
	 * For serialization purposes. Auto generated by Eclipse
	 */
	private static final long serialVersionUID = 4974881225896539304L;

	public EnodeBComponentEvent(Object source, int id, String command) {
		super(source, id, command);
	}



}
