package UE;

import java.awt.event.ActionEvent;

public class UeEvent extends ActionEvent {

	/**
	 * For serialization purposes. Auto generated by Eclipse
	 */
	private static final long serialVersionUID = 7281845006279177297L;

	public UeEvent(Object source, int id, String command) {
		super(source, id, command);
	}

}
